# Generated by Django 2.1.5 on 2019-08-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyvolunteer', '0002_auto_20190724_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codeNum',
            field=models.DateTimeField(blank=True, null=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNum',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='전화번호'),
        ),
    ]
