# Generated by Django 2.1.5 on 2019-08-07 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easyvolunteer', '0004_auto_20190806_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1, verbose_name='레벨'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organ',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_organ', to='easyvolunteer.Organ', verbose_name='기관 정보'),
        ),
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=0, verbose_name='포인트'),
        ),
    ]
